# Introduction to numpy, pandas, and matplotlib

In [1]:
# These are dictionaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Check that these are modules we imported:
np, pd, plt

(<module 'numpy' from '/Users/audrabuysse/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>,
 <module 'pandas' from '/Users/audrabuysse/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py'>,
 <module 'matplotlib.pyplot' from '/Users/audrabuysse/opt/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py'>)

# Numpy datatypes

In [ ]:
# numpy gives you an array of a particular datatype

## float32

In [10]:
x = np.float32(2 ** 127)
x, type(x)

(1.7014118e+38, numpy.float32)

## float64

In [16]:
x = np.float64(2 ** 1023)
x, type(x)

(8.98846567431158e+307, numpy.float64)

## arrays have a fixed datatype: 

In [18]:
lst = [1.,2.,3.,4.,5.]
array = np.array(lst)
array, type(array), array.dtype

(array([1., 2., 3., 4., 5.]), numpy.ndarray, dtype('float64'))

In [24]:
# np.arange creats array similar to how we would use a for loop // 
# generator to create a list
start = 0 
end = 100
interval = 4
range_array = np.arange(start,end + 1, interval)
range_array

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [22]:
# Before we were making lists like this: 
range_list = [i for i in range(0,101)]
range_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100]

# Two dimensional lists and arrays

# Create two dimensional list

In [26]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# transform that two dimensional list to a two dimensional array

In [27]:
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
two_dim_array = np.array(list_of_lists)
two_dim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Call the 0th row of the two_dim_array

In [29]:
two_dim_array[0]

array([1, 2, 3])

In [ ]:
# call the 0th element of the 0th row:

In [40]:
two_dim_array[0][0]

1

In [ ]:
# call the 1st element of the 0th row:

In [39]:
two_dim_array[0][1]

2

# use a for loop to call the first index in the two_dim_array as i 

# calling two_dim_array[i] will yield the ith row

In [41]:
for i in range(len(two_dim_array)):
    print(i)
    print(two_dim_array[i])

0
[1 2 3]
1
[4 5 6]
2
[7 8 9]


## passing the row to a second for loop will cycle through
# the second (row) index as j. Calling row[j] will yield
# the j^(th) value from the row

In [36]:
print("i,j:")
for i in range(len(two_dim_array)):
    row = two_dim_array[i]   
    for j in range(len(row)):
        print(i,j)
        print(row[j])
        print("val:", row[j])

i,j:
0 0
1
val: 1
0 1
2
val: 2
0 2
3
val: 3
1 0
4
val: 4
1 1
5
val: 5
1 2
6
val: 6
2 0
7
val: 7
2 1
8
val: 8
2 2
9
val: 9


In [38]:
for row in two_dim_array:
    print(row)
    for val in row:
        print(val)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


# np.zeros(), np.ones(), np.empty
# np.zeros_like(ex: list/array), np.ones_like(), np.empty_like

In [42]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.empty((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [46]:
l = list_of_lists
np.zeros_like(l)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [47]:
np.ones_like((l))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [48]:
np.empty_like(l)

array([[           0,            0, 481036337261],
       [519691042932, 171798691880, 206158430257],
       [210453397548, 176093659184,           41]])

# log values

In [49]:
np.log(1)

0.0

In [50]:
np.log(np.e)

1.0

In [51]:
np.log(two_dim_array)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [52]:
np.log10(two_dim_array)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [53]:
# Special values of numpy:

In [56]:
pi = np.pi
e = np.e
lne = np.log(e)
infinity = np.inf
null_val = np.nan
pi, e, lne, infinity, null_val

(3.141592653589793, 2.718281828459045, 1.0, inf, nan)